name: clock-in

on:
  workflow_dispatch:
  schedule:
    - cron: "58 0 * * 1-5"
    - cron: "58 5 * * 1-5"

jobs:
  clock-in:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel requests
      - name: Clock In
        env:
          USERID: ${{ secrets.USERID }}
          XAPIKEY: ${{ secrets.XAPIKEY }}
        run: python clock.py in